name: my-custom-actions

on:
    workflow_dispatch:

jobs:
    my-custom-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: using composite action
              uses: ./.github/actions/composit-actions/
              with:
                example-input: "This is a custom input value"
              