name: github-context-demo
run-name: kamal-${{github.sha}}-${{github.run_number}}

on:
    #push:
    workflow_dispatch:
        inputs: 
            age: 
                type: string
                default: "23"
                description: "this the age of patan"
            height: 
                type: string
                default: "6.0"
                description: "this the height of patan"

    
env: 
    var1: "pavan"
    var2: "pathan"

jobs:

    job1:

      runs-on: ${{vars.imageVersion}}

      env: 
        var3: "akhil"
        var2: "pathan basha khan"

      steps:
      - name: step1
        env:
            var4: "digistack"
            var1: "pavan ramana"
        run: |
            echo "hii ${{env.var1}}" 
            echo "byee ${{env.var2}}"
            echo "ok ${{env.var3}}"
            echo "employees of  ${{env.var4}}"

      - name: step2
        env: 
            my_secret: ${{secrets.aws_access_key}}
        run: |
            echo "${{vars.message}}"
            echo "my secret is ${{env.my_secret}}"
            echo "${{inputs.age}} and ${{inputs.height}}"



    