name: github-context-demo

on:
    push:
    workflow_dispatch:
    
env: 
    var1: "pavan"
    var2: "pathan"

jobs:

    job1:

      runs-on: ubuntu-latest

      env: 
        var3: "akhil"

      steps:
      - name: step1
        env:
            var4: "digistack"
        run: |
            echo "hii ${{env.var1}}" 
            echo "byee ${{env.var2}}"
            echo "ok ${{env.var3}}"
            echo "employees of  ${{env.var4}}"

    