name: github-context-demo

on:
    push:
    workflow_dispatch:
    
env: 
    var1: "pavan"
    var2: "pathan"

jobs:

    job1:

      runs-on: ubuntu-latest

      steps:
      - name: step1
        run: |
            echo "hii ${{env.var1}}" 
            echo "byee ${{env.var2}}"
            echo "ok akhil"

    