name: nodeJS-workflow

on:
    workflow_dispatch:

jobs:
    nodejs-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version: 24

            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v5
              with:
                path: ./node_modules
                key: npm-cache-${{ hashFiles('**/package-lock.json') }}
            - name: install dependencies
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm ci
            - name: cache hit message
              if: steps.cache-npm.outputs.cache-hit == 'true'
              run: echo "Cache hit! Skipping npm install."
            - name: build
              run: npm run build
            - name: upload build artifact
              uses: actions/upload-artifact@v7
              with:
                name: build
                path: ./dist