name: techbyte-wf

on:
    #push:
    workflow_dispatch: 

jobs:
    job1:

        runs-on: ubuntu-latest
        outputs:
            op1: ${{steps.pv.outputs.name}}
          
        steps:
            - name: step1
              id: pv 
              run: | 
                echo "name=pavan" >> "$GITHUB_OUTPUT"
                echo "job=devops" >> "$GITHUB_OUTPUT"

            - name: step2
              run: echo "${{steps.pv.outputs.name}}-job-${{steps.pv.outputs.job}}"


    job2:
        runs-on: ubuntu-slim
        needs: job1
        steps:
            - name: step1
              run: | 
                echo "${{needs.job1.outputs.op1}}"